services: 
  backend:
    build:
      context: ./back 
      - "8080:8080" 
    networks:
      - orion-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev   
  frontend:
    build:
      context: ./front 
    ports:
      - "80:80"
    networks:
      - orion-network
    depends_on:      - backend 

networks:
  orion-network:
    driver: bridge
