services:
  backend:
    build:
      context: ./back
    ports:
      - "8080:8080"
    networks:
      - orion-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - LOGSTASH_HOST=orion-logstash
  frontend:
    build:
      context: ./front
    ports:
      - "4200:8080"
    networks:
      - orion-network
    depends_on:
      - backend
networks:
  orion-network:
    name: orion-global-network
    external: true
