input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "orion-backend-logs-%{+YYYY.MM.dd}"   
    ssl_verification_mode => "none"
  }
  stdout {
    codec => rubydebug
  }
}