name: Orion CI/CD Pipeline

on:
  push:
    branches: ["main", "ops/setup-ci-cd"]
  pull_request:
    branches: ["main"]

jobs:
  # ---------------------------------------------------------
  # JOB 1 : Tests du Front-end (Angular)
  # ---------------------------------------------------------
  frontend-test:
    name: Front-end Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installation propre des dépendances
        run: npm ci

      - name: Exécution des tests Angular
        run: npm run test:ci

  # ---------------------------------------------------------
  # JOB 2 : Tests du Back-end (Spring Boot)
  # ---------------------------------------------------------
  backend-test:
    name: Back-end Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration de Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"

      - name: Ajout des droits d'exécution au wrapper Gradle
        run: chmod +x ./gradlew

      - name: Exécution des tests Spring Boot
        run: ./gradlew test
